// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.Dealer = (function(_super) {
    __extends(Dealer, _super);

    function Dealer() {
      return Dealer.__super__.constructor.apply(this, arguments);
    }

    Dealer.prototype.initialize = function(config) {
      return this.set({
        deck: new Deck()
      });
    };

    Dealer.prototype.giveCard = function(player) {
      return player.hand.add(deck.pop());
    };

    return Dealer;

  })(Backbone.Model);

}).call(this);
