// Generated by CoffeeScript 1.7.1
(function() {
  var Suit, clubs, diamonds, hearts, spades, suits;

  Suit = (function() {
    function Suit() {}

    return Suit;

  })();

  diamonds = new Suit();

  spades = new Suit();

  clubs = new Suit();

  hearts = new Suit();

  suits = [diamonds, spades, clubs, hearts];

}).call(this);
